# Generated by Django 4.1.5 on 2023-01-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hour',
            field=models.DateTimeField(),
        ),
    ]
