# Generated by Django 4.1.5 on 2023-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_owner', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
            ],
        ),
    ]
